web/Controllers/ProduitBackController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using data;
using domain;
using System.IO;

namespace web.Controllers
{
    public class ProduitBackController : Controller
    {
        private PidevContext db = new PidevContext();

        // GET: ProduitBack
        public ActionResult Index()
        {
           

            return View(db.Produits.ToList());
        }

        // GET: ProduitBack/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // GET: ProduitBack/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProduitBack/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idProduit,prix,description,dateProd,categorie,FileName,FileContent,Files,image,imagePath")] Produit produit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    String FileExt = Path.GetExtension(produit.Files.FileName).ToUpper();
                    if (FileExt == ".PDF")
                    {
                        Byte[] data = new byte[produit.Files.ContentLength];
                        produit.Files.InputStream.Read(data, 0, produit.Files.ContentLength);
                        produit.FileName = produit.Files.FileName;
                        produit.FileContent = data;
                    }
                    string fileName = Path.GetFileNameWithoutExtension(produit.image.FileName);
                    string extension = Path.GetExtension(produit.image.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff")+extension;
                    produit.imagePath = "~/Image/" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Image/"), fileName);
                    produit.image.SaveAs(fileName);

                    db.Produits.Add(produit);
                    db.SaveChanges();
                    db.SaveChanges();

                    ModelState.Clear();
                    return RedirectToAction("Index");

                }
            }
            catch
            {

            }
            
            return View(produit);
        }

        // GET: ProduitBack/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // POST: ProduitBack/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idProduit,prix,description,dateProd,categorie,FileName,FileContent,Files,image,imagePath")] Produit produit)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    String FileExt = Path.GetExtension(produit.Files.FileName).ToUpper();
                    if (FileExt == ".PDF")
                    {
                        Byte[] data = new byte[produit.Files.ContentLength];
                        produit.Files.InputStream.Read(data, 0, produit.Files.ContentLength);
                        produit.FileName = produit.Files.FileName;
                        produit.FileContent = data;
                    }
                    string fileName = Path.GetFileNameWithoutExtension(produit.image.FileName);
                    string extension = Path.GetExtension(produit.image.FileName);
                    fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                    produit.imagePath = "~/Image/Produits" + fileName;
                    fileName = Path.Combine(Server.MapPath("~/Image/Produits"), fileName);
                    produit.image.SaveAs(fileName);



                    ModelState.Clear();

                    db.Entry(produit).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
            }
            catch
            {

            }
           
            return View(produit);
        }

        // GET: ProduitBack/Delete/5
        public JsonResult Delete(int id)
        {

            bool result = false;
            Produit u = db.Produits.Where(x => x.idProduit == id).FirstOrDefault();
            if (u != null)
            {
                db.Produits.Remove(u);
                db.SaveChanges();
                result = true;
            }

            return Json(result, JsonRequestBehavior.AllowGet);
        }

       

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

web/Views/ProduitBack/Create.cshtml
@model domain.Produit

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">

    <h5 class="card-header">Nouveau document</h5>

    @using (Html.BeginForm("Create", "ProduitBack", FormMethod.Post, new { enctype = "multipart/form-data", id = "validationform" }))
    {
        @Html.AntiForgeryToken()

        <div class="card-body">

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">Prix</label>
                <div class="col-12 col-sm-8 col-lg-6">
                    @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control", placeholder = "donner le prix*" } })
                    @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">Description</label>
                <div class="col-12 col-sm-8 col-lg-6">
                    @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "donner la description*" } })
                    @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">Image</label>
                <div class="col-12 col-sm-8 col-lg-6">
                   <input type="file" name="image" required />
                </div>
            </div>

            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">Date de production</label>
                <div class="col-12 col-sm-8 col-lg-6">
                    @Html.EditorFor(model => model.dateProd, new { htmlAttributes = new { @class = "form-control", placeholder = "donner la date de production*" } })
                    @Html.ValidationMessageFor(model => model.dateProd, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">Categorie</label>
                <div class="col-12 col-sm-8 col-lg-6">
                    @Html.EnumDropDownListFor(model => model.categorie, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.categorie, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group row">
                <label class="col-12 col-sm-3 col-form-label text-sm-right">File</label>
                <div class="col-12 col-sm-8 col-lg-6">
                    @Html.TextBoxFor(model => model.Files, new { @type = "file", @multiple = "multiple" })
                    @Html.ValidationMessageFor(model => model.Files)
                </div>
            </div>
            <div class="form-group row text-center">
                <div class="col-md-offset-2 col-md-10">
                    <a href="javascript:document.getElementById('validationform').submit();" onclick="javascript: myFunction();" class="btn btn-space btn-primary">Create</a>
                    <a href="/ProduitBack/Index" class="btn btn-space btn-secondary">Annuler</a>
                </div>
            </div>
        </div>
    }
</div>
<script>
    var form = document.getElementById('validationform');

    function myFunction() {
        if (form.checkValidity()) {
            alert("Produit creer avec succes !!!!!");
        }
    }
</script>

web/Views/ProduitBack/Edit.cshtml
@model domain.Produit

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}



@using (Html.BeginForm("Edit", "ProduitBack", htmlAttributes: new { id = "validationform" }, method: FormMethod.Post))
{
    @Html.AntiForgeryToken()



    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.idProduit)

    <div class="card-body">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">Prix</label>
            <div class="col-12 col-sm-8 col-lg-6">
                @Html.EditorFor(model => model.prix, new { htmlAttributes = new { @class = "form-control", placeholder = "donner le prix*" } })
                @Html.ValidationMessageFor(model => model.prix, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">Description</label>
            <div class="col-12 col-sm-8 col-lg-6">
                @Html.EditorFor(model => model.description, new { htmlAttributes = new { @class = "form-control", placeholder = "donner la description*" } })
                @Html.ValidationMessageFor(model => model.description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">Image</label>
            <div class="col-12 col-sm-8 col-lg-6">
                <input type="file" name="image" required />
            </div>
        </div>

        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">Date de production</label>
            <div class="col-12 col-sm-8 col-lg-6">
                @Html.EditorFor(model => model.dateProd, new { htmlAttributes = new { @class = "form-control", placeholder = "donner la date de production*" } })
                @Html.ValidationMessageFor(model => model.dateProd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">Categorie</label>
            <div class="col-12 col-sm-8 col-lg-6">
                @Html.EnumDropDownListFor(model => model.categorie, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.categorie, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group row">
            <label class="col-12 col-sm-3 col-form-label text-sm-right">File</label>
            <div class="col-12 col-sm-8 col-lg-6">
                @Html.TextBoxFor(model => model.Files, new { @type = "file", @multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.Files)
            </div>
        </div>
        <div class="form-group row text-center">
            <div class="col-md-offset-2 col-md-10">
                <a href="javascript:document.getElementById('validationform').submit();" onclick="javascript: myFunction();" class="btn btn-space btn-primary">Modifier</a>
                 <a href="/ProduitBack/Index" class="btn btn-space btn-secondary" >Annuler</a>
            </div>
        </div>
    </div>

    

}

<script>
    var form = document.getElementById('validationform');

    function myFunction() {

        if (form.checkValidity()) {

            alert("Produit modifier avec succes !");
        }
    }
</script>

web/Views/ProduitBack/Index.cshtml
@model IEnumerable<domain.Produit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h2 style="text-align:center;color:aqua;" class="pageheader-title">Gestion documents </h2>
            @Html.ActionLink("Create New", "Create", new { @class = "btn btn-space btn-primary" })
        </div>
    </div>
</div>

<table class="table">
    <thead class="bg-light">
        <tr class="border-0">

            <th>
                @Html.DisplayNameFor(model => model.prix)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dateProd)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.categorie)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FileName)
            </th>
            <th>Action</th>
        </tr>
    </thead>
    @foreach (var item in Model)
    {
        @Html.Hidden("itemid", item.idProduit, new { id = "itemid" })
    <tr id="row_@item.idProduit">
        <td>
            @Html.DisplayFor(modelItem => item.prix)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.description)
        </td>
        <td>
           <img src="@Url.Content(item.imagePath)" width="50" height="50"/>
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dateProd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.categorie)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>
        
        <td>
          
            <a href="#" onclick="ConfirmDelete(@item.idProduit)">Supprimer</a>
        </td>
    </tr>
    }

</table>
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <a href="#" class="close" data-dismiss="modal">&times;</a>
                <h3 class="modal-title">Supprimer !</h3>
            </div>
            <div class="modal-body">
                <h4>Voulez-vous supprimer cet produit ?? </h4>

                <div style="text-align:center;display:none" id="loaderDiv">
                    <img src="~/Content/InternetSlowdown_Day.gif" width="150" />
                </div>

            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-default" data-dismiss="modal">Annuler</a>
                <a href="#" class="btn btn-success" onclick="DeleteProd()">Confirmer</a>
            </div>

        </div>

    </div>
    @*hidden field for storing current userId*@
    <input type="hidden" id="hiddenEmployeeId" />
</div>
<script src="~/Scripts/jquery-3.3.1.min.js"></script>

<script src="~/Scripts/bootstrap.min.js"></script>
<script>

    var ConfirmDelete = function (EmployeeId) {

        $("#hiddenEmployeeId").val(EmployeeId);
        $("#myModal").modal('show');

    }

    var DeleteProd = function () {

        // $("#loaderDiv").show();

        var empId = $("#hiddenEmployeeId").val();

        $.ajax({

            type: "POST",
            url: "/ProduitBack/Delete/",
            data: { id: empId },
            success: function (result) {
                $("#loaderDiv").hide();
                $("#myModal").modal("hide");
                $("#row_" + empId).remove();

            }

        })

    }
</script>