web/Controllers/ProduitController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using data;
using domain;


namespace web.Controllers
{
    public class ProduitController : Controller
    {
        private PidevContext db = new PidevContext();

        // GET: Produit
        //[Authorize]
        public ActionResult Index()
        {
            return View(db.Produits.ToList());
        }
        public ActionResult getProdByCateg(string categ)
        {
            var listByCateg = db.Produits.Where(x => x.categorie.ToString() == categ).ToList();
            return Json(listByCateg, JsonRequestBehavior.AllowGet);
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

web/Controllers/ShoppingCartController.cs
using data;
using domain;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using web.Models;
namespace web.Controllers
{
    public class ShoppingCartController : Controller
    {
        PidevContext db = new PidevContext();
        // GET: ShoppingCart
        public ActionResult Index()
        {

            return View();
        }
        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Pr.idProduit == id)
                    return i;
            return -1;
        }
        public ActionResult Delete(int idProd)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            
            if (Session["cart"] != null)
            {
                int index = isExisting(idProd);
                Item item = new Item();
                if (index != -1)
                {
                    if (cart[index].Quantity > 1)
                    {
                        cart[index].Quantity--;
                    }
                    else
                    {
                        cart.RemoveAt(index);
                    } 
                }
                Session["cart"] = cart;
            }
             
            return RedirectToAction("Index", "Produit");
        }
        public ActionResult OrderNow(int id)
        {
            if(Session["cart"] == null)
            {
                
                List<Item> cart = new List<Item>();
                cart.Add(new Item(id,db.Produits.Find(id), 1, db.Produits.Find(id).imagePath));
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart =(List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                    cart.Add(new Item(id,db.Produits.Find(id), 1, db.Produits.Find(id).imagePath));
                else
                     
                    cart[index].Quantity++;
                
                Session["cart"] = cart;
            }
            return RedirectToAction("Index", "Produit");
            //return "ok";
            //return View("Cart");
        } 
    }
}

web/Views/Produit/Index.cshtml
@model IEnumerable<domain.Produit>

@{


    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<section id="shop" class="htc__product__area ptb--130 bg__white">
    <div class="htc__product__container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product__menu">
                        <button data-filter="*" class="is-checked">Tous</button>
                        <button  class="c">Series</button>
                        <button  class="c">Cours</button>
                        <button  class="c">Examens</button>
                    </div>
                </div>
            </div>
                <div class="row">
                    <div class="product__list">
                        @foreach (var item in Model)
                        {
                            <!-- Start Single Product -->
                            <div class="col-md-3 single__pro col-lg-3 cat--1 col-sm-4 col-xs-12">
                                <div class="product foo">
                                    <div>
                                        <div class="product__inner">
                                            <div class="pro__thumb">
                                                <a href="#">
                                                    <img src="@Url.Content(item.imagePath)" width="200" height="200" />
                                                </a>
                                            </div>
                                            <div class="product__hover__info">
                                                <ul class="product__action">
                                                    <li><a data-toggle="modal" data-target="#productModal-@item.idProduit" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>
                                                    @if (Request.IsAuthenticated)
                                                    {
                                                        <li><a href="@Url.Action("OrderNow", "ShoppingCart", new { id = item.idProduit })"><span class="ti-shopping-cart"></span></a></li>
                                                    }
                                                </ul>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="product__details">
                                        <h2></h2>
                                        <span class="popular__pro__prize"> </span>
                                        <h2>
                                            <a href="product-details.html"> @Html.DisplayFor(modelItem => item.description) </a>
                                            @{ViewBag.description = item.description;}
                                        </h2>
                                        <ul class="product__price">

                                            <li class="new__price">@Html.DisplayFor(modelItem => item.prix) dt</li>
                                            @{ViewBag.prix = item.prix;}
                                        </ul>
                                        <div hidden>
                                            @Html.DisplayFor(modelItem => item.categorie)
                                            @{ViewBag.categorie = item.categorie;}
                                        </div>
                                        <div hidden class="categorie">@{ViewBag.categorie = item.categorie.ToString();}</div>
                                    </div>

                                </div>
                            </div>

                            <div class="modal fade" id="productModal-@item.idProduit" tabindex="-1" role="dialog">
                                <div class="modal-dialog modal__container" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header modal__header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        </div>
                                        <div class="modal-body">
                                            <div class="modal-product">
                                                <!-- Start product images -->
                                                <div class="product-images">
                                                    <div class="main-image images">

                                                        <img src="@Url.Content(item.imagePath)" width="200" height="200" />
                                                    </div>
                                                </div>
                                                <!-- end product images -->
                                                <div class="product-info">
                                                    <h1>Categorie : @ViewBag.categorie</h1>
                                                    <div class="price-box-3">
                                                        <div class="s-price-box">
                                                            <span class="new-price">@ViewBag.prix dt</span>
                                                        </div>
                                                    </div>
                                                    <div class="quick-desc">
                                                        @ViewBag.description
                                                    </div>
                                                </div>
                                            </div><!-- .product-info -->
                                        </div><!-- .modal-body -->
                                    </div><!-- .modal-content -->
                                </div><!-- .modal-dialog -->
                            </div>

                            <!-- End Single Product -->}
                    </div>
                </div>
            </div>
</section>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js"></script>

<script type="text/javascript">
    $(".check-mark").click(function () {
        var categorie = $('categorie').val();
        $.ajax({
        url: '@Url.Action("getProdByCateg", "ProduitController")',
        type: "GET",
        data: { categ: categorie },
            success: function (categ) {
             
            }
        });
});
</script>